### ISSUE TITLE
[DataCap Application] Triton One - Solana Transaction and Block History

### ISSUE THREAD

**Issue by Lusitaniae** [cryptowhizzard/Fil-A-1#1]
### Version

1

### DataCap Applicant

Triton One Limited

### Project ID

1111111111

### Data Owner Name

Triton One Limited

### Data Owner Country/Region

Isle of Man

### Data Owner Industry

Web3 / Crypto

### Website

https://triton.one

### Social Media Handle

https://twitter.com/triton_one

### Social Media Type

Twitter

### What is your role related to the dataset

Dataset Owner

### Total amount of DataCap being requested

5PiB

### Expected size of single dataset (one copy)

32GiB

### Number of replicas to store

4

### Weekly allocation of DataCap requested

150TiB

### On-chain address for first allocation

f3qqnndp7w3g7qfioy2n5jrw2xmo5cczp6ttkqndcocbpyp3gqlnq22vqgiliivwulc5vuewr7xn2u6s3fat4a

### Data Type of Application

Public, Open Dataset (Research/Non-Profit)

### Custom multisig

- [X] Use Custom Multisig

### Share a brief history of your project and organization

```text
Triton One was one of the first infrastructure providers working on Solana. We began by operating the public RPC nodes that were made available freely to the Solana ecosystem in 2021. Since then we have been an active stakeholder in many Solana projects including ensuring the replication and development of historical archives for Solana. This project seeks to make available a fully queryable historical archive of Solana data on Filecoin.
```

### Is this project associated with other projects/ecosystem stakeholders?

Yes

### If answered yes, what are the other projects/ecosystem stakeholders

```text
This effort is done in collaboration with the Solana Foundation,the Firedancer team at Jump Crypto and the Protocol Labs Outercore Network Growth team. We have also initiated partnerships with other stakeholders in the Solana ecosystem, such as other infrastructure providers who have pledged support and interest in maintaining and using this dataset.

In parallel to this project, there is an effort to upload historical ledger files that have been snapshotted from Solana (https://github.com/filecoin-project/filecoin-plus-large-datasets/issues/923). The historical ledger archives that this other effort seeks to upload are a snapshot in time of the database generated by a Solana validator. The project described in this proposal seeks to upload historical archives in a format that allows data to be accessed semantically and directly by producing a content based DAG based on the logical elements of Solana’s blockchain (blocks, transactions and shreds).
```

### Describe the data being stored onto Filecoin

```text
Solana blockchain data - daily data dumps of blocks and transactions produced by the validators of the chain.
```

### Where was the data currently stored in this dataset sourced from

Other

### If you answered "Other" in the previous question, enter the details here

```text
We maintain archive nodes that keep continuous records of all blocks storing copies of these records in S3 compatible storage.
```

### If you are a data preparer. What is your location (Country/Region)

Isle of Man

### If you are a data preparer, how will the data be prepared? Please include tooling used and technical details?

```text
Solana data is natively represented in IPLD format and can be exported directly as CAR files. There is no additional data preparation required.

IPLD schema: https://github.com/firedancer-io/radiance/blob/main/pkg/ipld/ipldsch/ipldsch_types.go
Car generator: https://github.com/firedancer-io/radiance/blob/main/pkg/ipld/cargen/cargen.go.
```

### Has this dataset been stored on the Filecoin network before? If so, please explain and make the case why you would like to store this dataset again to the network. Provide details on preparation and/or SP distribution.

```text
No
```

### Please share a sample of the data

```text
Solana blockchain data: https://console.cloud.google.com/storage/browser/mainnet-beta-ledger-us-ny5
```

### Confirm that this is a public dataset that can be retrieved by anyone on the Network

- [X] I confirm

### What is the expected retrieval frequency for this data

Monthly

### For how long do you plan to keep this dataset stored on Filecoin

Permanently

### In which geographies do you plan on making storage deals

Greater China, Asia other than Greater China, North America, Europe

### How will you be distributing your data to storage providers

Cloud storage (i.e. S3), HTTP or FTP server

### How did you find your storage providers

Others

### If you answered "Others" in the previous question, what is the tool or platform you used

```text
We will be participating in the Spade pilot with the Network Growth team. This will automate matching us to SPs that meet our requirements in terms of replication, geography, retrievability, etc.
```

### Please list the provider IDs and location of the storage providers you will be working with.

```text
n/a
```

### How do you plan to make deals to your storage providers

Boost client

### Can you confirm that you will follow the Fil+ guideline

Yes

**Comment by cryptowhizzard** [comment]
Hello,

As per request, please provide another wallet adres.
